on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ runner.os }}
      - run: |
          cargo run -- --help
          cargo test

  test-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bash fish zsh

      - name: Run bash test
        run: env -i PATH="$PATH" bash scripts/test.bash

      - name: Run zsh test
        run: env -i PATH="$PATH" zsh scripts/test.zsh

      - name: Run fish test
        run: env -i PATH="$PATH" fish scripts/test.fish
